<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Carrinho' => $baseDir . '/model/Carrinho.class.php',
    'Categorias' => $baseDir . '/model/Categorias.class.php',
    'Clientes' => $baseDir . '/model/Clientes.class.php',
    'Conexao' => $baseDir . '/model/Conexao.class.php',
    'Config' => $baseDir . '/model/Config.class.php',
    'Correios' => $baseDir . '/model/Correios.class.php',
    'EnviarEmail' => $baseDir . '/model/EnviarEmail.class.php',
    'ImageUpload' => $baseDir . '/model/ImageUpload.class.php',
    'Itens' => $baseDir . '/model/ItensPedido.class.php',
    'Login' => $baseDir . '/model/Login.class.php',
    'PHPMailer\\PHPMailer\\PHPMailer' => $baseDir . '/model/PHPMailer.php',
    'Paginacao' => $baseDir . '/model/Paginacao.class.php',
    'Pedidos' => $baseDir . '/model/Pedidos.class.php',
    'Produtos' => $baseDir . '/model/Produtos.class.php',
    'ProdutosImages' => $baseDir . '/model/ProdutosImages.class.php',
    'Rotas' => $baseDir . '/model/Rotas.class.php',
    'Sistema' => $baseDir . '/model/Sistema.class.php',
    'Template' => $baseDir . '/model/Template.class.php',
);
